spring.application.name=demo

supabase.url=${SUPABASE_URL}
supabase.publishable-key=${SUPABASE_PUBLISHABLE_KEY}
supabase.secret-key=${SUPABASE_SECRET_KEY}
supabase.jwks-url=${SUPABASE_JWKS_URL}

bidhouse.usuario-actual-email=alejandro@bidhouse.com

spring.mvc.problemdetails.enabled=true
